### ISSUE TITLE
[linux] Packaging

### ISSUE THREAD

**Issue by handicraftsman** [google/flutter-desktop-embedding#113]
Any plans on packaging (.deb/.rmp/.tar.gz) script support?

**Comment by stuartmorgan** [comment]
The focus is on functionality at this point, so there are no specific plans around distribution.

Are you talking about the framework, or applications built using the framework?

**Comment by handicraftsman** [comment]
Applications built using the framework. I think there should be at least a way of setting package's source directory - ../package_name is not the best path. Especially in AppImages.

**Comment by stuartmorgan** [comment]
> I think there should be at least a way of setting package's source directory
There is; it's one of the arguments to CreateFlutterWindow*

> ../package_name is not the best path
The Linux example app is currently not showing how something intended for distribution would be configured, which is essentially what is tracked by issue #76. But while I would like the example to show a better model to follow, nothing about the API requires using the same paths as the example app currently does.

I'm not sure that scripts to actually package applications for distribution will ever be in scope for this project, since there are many possible ways someone might choose to package an application.

**Comment by gedw99** [comment]
Yeah its a pity because packaging is a tough problem sometimes.

At least a basic packager for each platform could be a nice stretch goal.

**Comment by stuartmorgan** [comment]
Is there some reason packaging a Linux application built with Flutter would require a different solution that packaging any other Linux application? The dependencies don't seem particularly exotic: some libraries and some resources, just like any other non-trivial application.

If packaging is a hard problem, presumably there are existing projects that attempt to solve it. Why wouldn't they be applicable here?

**Comment by charafau** [comment]
It would be better to make some post / wiki how to package this in flatpak.

**Comment by stuartmorgan** [comment]
With #76 fixed it should be much clearer what's necessary for distribution.

I'm going to close this per my comments above, but if there are specific problems with using existing packaging solutions now that the example is clearer, please comment and I can reconsider.
