### ISSUE TITLE
MethodChannel for platform side

### ISSUE THREAD

**Issue by pauldemarco** [google/flutter-desktop-embedding#145]
Often times a method channel is created on the platform side to call methods up in Dart space.

Android and iOS allow for the creation of these channel's with MethodChannel, see here: https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/MethodChannel.java

This library only currently works for request/response from Dart -> Platform.

**Comment by krisgiesing** [comment]
See also #102, perhaps the functionality here is covered by that?

**Comment by stuartmorgan** [comment]
Yes, #102 covers this. MethodChannel was already added on macOS, in fact (https://github.com/google/flutter-desktop-embedding/blob/master/library/macos/FLEChannels.h), although it's currently used as implementation detail of the legacy plugin API. The primary work left in #102 is to do the same on Linux, then do a breaking change on both platforms to replace the current plugin registration with something that looks much more like the Android and iOS channel registration system. (I actually have the remaining macOS change mostly implement in a local branch, but am holding off on it to do Linux at the same time.)

> This library only currently works for request/response from Dart -> Platform.

This isn't exactly true. The current API is certainly set up primarily for that, but there's nothing preventing someone from creating a Plugin subclass that has a public method implemented in terms of `InvokeMethod(...)` (on Linux) or having arbitrary code call `invokeMethod:arguments:onChannel:withCodec:` (on macOS). The color_panel plugin in this repository calls a method from native to Dart internally, so the plumbing is all in place and tested. It'll certainly be much cleaner once #102 is done, and will be much more familiar to existing Flutter developers, but it you can experiment with the functionality now.

One significant caveat is https://github.com/flutter/flutter/issues/18852 which needs to be fixed on the Flutter side. However, for now you can work around that by using a callback from Dart to platform instead of a return value.

**Comment by stuartmorgan** [comment]
In fact, on macOS you can create an FLEMethodChannel (the FLEViewController is the `binaryMessenger`) and use the method channel interface already for platform -> Dart, without waiting for the refactor. You just can't yet directly register a channel for Dart -> platform communication without using the legacy plugin API.

**Comment by pauldemarco** [comment]
Awesome, thanks for taking the time to fill me in on all that. Looking
forward to #102!

**Comment by baldemir** [comment]
@pauldemarco @stuartmorgan When I want to create a FlutterMethodChannel on macOS, FlutterViewController doesn't have the field binaryMessenger. So how can I create the binaryMessenger for MethodChannel?
