### ISSUE TITLE
Support printing

### ISSUE THREAD

**Issue by gedw99** [google/flutter-desktop-embedding#15]
Wondering if the team think printing should be a plug-in or incorporated ?

At the moment I use golang code to print stuff on desktops because it's easy to do cross platform.
On flutter mobile I use sharing.

**Comment by krisgiesing** [comment]
If by "incorporated" you mean built into the Flutter engine itself, that's something the Flutter team would need to decide to do. From the perspective of this project, it would be a plug-in. Thanks for filing the issue - it will be interesting to see how many folks want this functionality.

**Comment by gedw99** [comment]
yes that is what i means by "incorporated". Lets call it built in.

**Comment by gedw99** [comment]
As I understand it flutter is based on Skia. Skia is the rendering engine.

Skia is used in Google chrome to render your web page. Skia has a library inside called pdfium that is able to output PDF ( and XPS for windows printers ).

So why does flutter do the same ?

I would really appreciate if the flutter team looked at this. Printing is a really needed aspect for me.

**Comment by stuartmorgan** [comment]
> Skia has a library inside called pdfium

This is not correct; pdfium is not part of Skia.

> that is able to output PDF

pdfium is a PDF viewer, which is largely orthogonal to printing (Chromium's ability to print predates pdfium).

> I would really appreciate if the flutter team looked at this.

If you want printing functionality within Flutter itself, you should file a feature request with Flutter. As the project readme says, this project is not part of Flutter. As Kris noted above if implemented within this project (which is what this bug tracks) it would be as a plugin.

**Comment by gedw99** [comment]
Ok i raised the Issue in the main Flutter repo.

https://github.com/flutter/flutter/issues/15457

Thanks.

**Comment by awdavies** [comment]
Closing for cleanup.

**Comment by awdavies** [comment]
Woops!  Misunderstood what this was about.  Reopening.

**Comment by stuartmorgan** [comment]
As the desktop effort has evolved and the focus is on moving things out of FDE, there's more clarity on what plugins would be implemented here. Specifically, unless something is either
- a temporary prototype/placeholder for something I strongly expect to become part of the Flutter framework, or
- a desktop implementation of an existing plugin, for platforms where the API hasn't stabilized enough that hosting them elsewhere makes sense yet

it should be developed somewhere other than this repository. That gives every plugin here a clear path for being moved out of the FDE repository later.

Since printing doesn't fall into either category, I'm going to close this. It seems like a great candidate for someone to develop as a community plugin though.

**Comment by silwalujjwal8** [comment]
how can we do usb printing in flutter desktop

**Comment by anandsubbu007** [comment]
Is there any update about direct printing in windows desktop?

**Comment by csells** [comment]
Printing is not on our current roadmap for desktop. There all packages on pub.dev for creating PDF files that you may find useful instead.
