### ISSUE TITLE
Use a tree manager (e.g., gclient) to manage dependencies

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#152]
Would it be a good idea to start using depot_tools DEPS system for the dependencies in the third_party folder to remove the dependencies from the repo?
This would also help us track specific supported versions of flutter in the future by either tracking by branch, version tag or with an autoroller and a testing system to add the latest supported commit hash to the DEPS file. Currently, we have to manually update each the third party dependencies in the repo and assume that the master Flutter tree is working so this could help with stopping breakages hitting users.
More of a forward thought than a necessity but just asking for thoughts.

**Comment by stuartmorgan** [comment]
I've considered this, but there are significant drawbacks. First, depot_tools is a fairly heavy added pre-req for a project of this small scale. Second, as currently structured, this project is something another project would depend on, and having projects you depend on force you to use another layer of dependency management tools gets very messy. (The latter will likely be much less of an issue once this project is more stable, at which point I expect it would go to a more Flutter-like approach of publishing a prebuilt SDK that most clients would consume rather than building from source.)

> This would also help us track specific supported versions of flutter in the future

I definitely don't want to use a DEPS-like structure to do this, since it would force the flutter checkout to be subordinate to this repo, whereas I think a much more flexible model is for this to essentially be an add-on. Consider the case, for instance, where a complex project using gclient is already managing a Flutter dependency via DEPS and then wants to use this project as well. What's needed in that case is a way for someone to know what version to roll their pin of this project to when rolling their Flutter pin (which tags would make easy).

My current thinking on supported version handling is to add, after each stable Flutter release, a corresponding tag to this repo indicating that that version of this project is compatible with the given Flutter release.

(The reason I'm not doing that now is that this project is still in such early stages that the idea of a "stable" or "supported" version doesn't make sense yet, and I expect changes that require bleeding-edge Flutter versions--richer mouse event APIs on the Flutter engine side, for instance--where I don't want progress to be slowed down by worrying about compatibility management.)

> and assume that the master Flutter tree is working

Eventually I would like to have a bot that's constantly building against Flutter master, and running a set of sanity tests on each platform, so that there's early detection of problems rather than it falling on whoever happens to run that latest version of Flutter first.

**Comment by CallumIddon** [comment]
Ok. Makes sense.

Closing.

**Comment by stuartmorgan** [comment]
I'm going to re-open this for tracking because I think it's very likely we'll want to do this in the future (after switching to an SDK model). I know from discussion with @clarkezone that Windows will have dependencies that need to be built from source, which will make this more of an issue.

At the point where clients would be expected to use prebuilt binaries, having a heavier process for setting up to build from source will be much less of an issue.

**Comment by stuartmorgan** [comment]
Now that the shells have moved (once the open PR lands), I no longer expect adding new third_party code here to be a concern going forward. GLFW won't be needed at all by this repo, jsoncpp should go away once the standard codec is available (in progress), and that just leaves the small amount of checked-in code, which I don't expect to change much if it all going forward. Where we do need a tree manager is for the shells, but the move to flutter/engine handled that.

Given that, closing.
