### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by amrboxit4me** [google/flutter-desktop-embedding#164]
I wonder when it will have IDE Plugin for building the project to target a specific desktop platform?

**Comment by stuartmorgan** [comment]
To make sure I'm understanding correctly, you're referring to being able to open a Flutter project in something like VS Code or IntelliJ and doing a build-and-run to launch the desktop version?

Ideally the approach for that will be to make the `flutter` tool extensible in a way that would allow existing IDE support to work with desktop, rather than writing new plugins for each IDE. I don't have a specific timeline for that, but it's certainly high on the priority list.

**Comment by amrboxit4me** [comment]
@stuartmorgan Yes that's what I mean exactly 
You know not everyone is advanced in building system and terminal and these things

**Comment by stuartmorgan** [comment]
There's nothing else tracking this yet, so it should definitely stay open.

**Comment by gabrc52** [comment]
I'm using a simple bash script and the `terminal-command-keys` plugin in the meantime: https://gist.github.com/gabrc52/ec0ea109322c816e7a81f0f58afabd24

**Comment by alexissantos** [comment]
+1 To this. Lookin' forward to it.

**Comment by stuartmorgan** [comment]
Moved to https://github.com/flutter/flutter/issues/30707 (and the related 30703-6)
