### ISSUE TITLE
[Windows] Plugin Support Not Exported

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#208]
The plugin support added in #161 isn't exported on Windows so isn't actually usable in other projects. It might be easier by adding a `__declspec` macro instead of using the `exports.def` file as you have to export the mangled names in some cases which isn't ideal.

@clarkezone do you have any insight on how to handle this?

**Comment by stuartmorgan** [comment]
Ah, right. I'll add an export macro and annotations, and turn on visibility hidden for Linux so they are handled consistently.

**Comment by clarkezone** [comment]
Sounds reasonable

**Comment by stuartmorgan** [comment]
Fixed in https://github.com/stuartmorgan/flutter-desktop-embedding/tree/library-visibility

It's built on PR #183 since doing it on master would create a bunch of conflicts between the two, so it'll need to wait for that to land. I'm expect that to be this week, but in the mean time that branch can be used for experimenting with external plugins.
