### ISSUE TITLE
[Windows] Scale Extremely Small

### ISSUE THREAD

**Issue by CallumIddon** [google/flutter-desktop-embedding#222]
Recently the scale of all flutter apps have become extremely small on Windows as shows below:

![capture](https://user-images.githubusercontent.com/19756675/50876986-b4760880-1434-11e9-9497-08e930e23db0.PNG)

**Comment by stuartmorgan** [comment]
What is this value for you?
https://github.com/google/flutter-desktop-embedding/blob/master/library/common/glfw/embedder.cc#L106

(On my Windows machine, everything was tiny before that change, and now it's reasonably sized, but perhaps there are edge cases that need to be accounted for.)

**Comment by CallumIddon** [comment]
`0.6`

**Comment by stuartmorgan** [comment]
Interesting. So technically that behavior is probably correct from a Flutter perspective, since if that's accurately representing the pixel density then this scaling would preserve size. However, it seems pretty surprising from a user perspective, so I'd be fine with clamping `pixel_ratio` to 1.0 at the low end.

(@GeertJohan FYI)

**Comment by franciscojma86** [comment]
I also see this on Linux. Clamping to 1.0 makes sense to me.
dpi = 94.1467
even.pixel_ratio = 0.588417
