### ISSUE TITLE
[flutter/plugins] Support url_launcher

### ISSUE THREAD

**Issue by shyndman** [google/flutter-desktop-embedding#224]
It would be great if we could add support for this plugin:
https://github.com/flutter/plugins/tree/master/packages/url_launcher

Thanks!

**Comment by stuartmorgan** [comment]
Definitely a good plugin to support.

This will be the first instance of adding only the desktop platform side of a plugin, with the Dart side coming from another repository, but I expect that there will be other common Flutter plugins that we'll want to do that with, so we'll need to figure out a good pattern for handling that (especially documenting what using them would look like).

**Comment by GregorySech** [comment]
Will a discussion be taken here about how to handle that aspect of plugin "extension" to desktop?  
  
if so my questions are:
- will the desktop embedding be integrated in the future into the current flutter/flutter repo/tooling? 
- how important is compatibility with the current flutter mobile app projects for the "extended" plugins?

**Comment by stuartmorgan** [comment]
> will the desktop embedding be integrated in the future into the current flutter/flutter repo/tooling?

I can't speak for the Flutter project as to their future plans. The scope of the discussion here is building out desktop support for `url_launcher` within the existing project structure.

> how important is compatibility with the current flutter mobile app projects for the "extended" plugins?

I'm not sure I understand the question; platform-side implementations for desktop platforms need to interoperate with the existing Dart code, or re-using the Dart side wouldn't work. Other than that I'm not sure what compatibility you have in mind.

Bear in mind that the goal here isn't to solve the much larger problem of creating a mobile-Flutter-plugin-like federated distribution system, with automated fetching and building. The implementation here will be within the existing structure of client projects manually pulling in plugin implementations.

**Comment by Hixie** [comment]
> will the desktop embedding be integrated in the future into the current flutter/flutter repo/tooling?

Yes. We're trying to plan out how to do this now.


(My recommendation would be to put the support in the plugin itself, not split into another repo. And as part of doing that, figure out how it should all work. :-) )

**Comment by GregorySech** [comment]
Ok I was thinking at a different problem.

I wanted to try to make it as painless as possible to take a current flutter app and provide indications to the embedder on where to find the platform implementation for its dependencies. 

This would be quite far from @Hixie 's recommendation and with hindsight it does seems like a "waste" of time once the majority of packages do provide said implementation.

**Comment by stuartmorgan** [comment]
There have been many changes since the discussion above, especially with respect to:
> (My recommendation would be to put the support in the plugin itself, not split into another repo. And as part of doing that, figure out how it should all work. :-) )

which is well underway.

However, it'll be a while before Linux and Windows have stable plugin APIs and `flutter` tooling support for plugins, so I've decided to temporary host implementations of some flutter/plugins desktop implementations here for now, all of which will migrate to official hosting as the APIs and tooling support is ready for them. That will allow people to experiment with desktop applications using those plugins earlier, without pushing the maintenance burden of unstable APIs onto another repo. (At this point this repo already has an interim structure+documentation for using plugins here, so doing so is straightforward.)

#433 will do this for `url_launcher` (with at least a couple of other simple plugins to follow).
