### ISSUE TITLE
Confused to get started on windows

### ISSUE THREAD

**Issue by harshapulikollu** [google/flutter-desktop-embedding#237]
I have gone through the `readme.md` file but I'm not confused here.
1. **Do I have to just place this repository under same directory where my flutter SDK resides?**
2. **Do I have to make changes to existing example code in this repository to make my app if not how can I create a new project for desktop** (CLI COMMAND)?
3.**How can I build the EXE of that app when it's completed development?**
*Please resolve my confusion such that as I'm eager to work with this. 
Thank you.*

**Comment by stuartmorgan** [comment]
Please use the mailing list rather than the issue tracker for general questions, as described in the README:
https://github.com/google/flutter-desktop-embedding#feedback-and-discussion
I would suggest reading [this thread](https://groups.google.com/forum/#!topic/flutter-desktop-embedding-dev/lYlLN04VRes) since I think it's likely relevant to your questions despite being about macOS rather than Windows.

1. That is the recommended setup, yes, as described in the README.
2. You don't have to; you are welcome to create a new project from scratch using whatever method you like. As for a CLI command for making a new project, there isn't one; please read [this section](https://github.com/google/flutter-desktop-embedding/blob/master/library/README.md#how-to-use-this-code).
3. It depends on what build system you choose to use for your project.
