### ISSUE TITLE
Add text input support to Linux

### ISSUE THREAD

**Issue by stuartmorgan** [google/flutter-desktop-embedding#24]
We need a text input implementation for the Linux embedder once the core implementation is fleshed out more.

**Comment by mrmcq2u** [comment]
org.freedesktop.IBus.Portal

**Comment by billy1380** [comment]
I understand that the linux version based on glfw is to be scrapped at some point and rewritten as a view but I am interested in just using GLFWKeyCallback and FlutterEngineSendPlatformMessage to send text to the flutter engine. There seems to be an issue with receiving platform messages at the minute.

I am using
``` c++
  FlutterProjectArgs args = {
    .struct_size = sizeof(FlutterProjectArgs),
    .assets_path = assets_path.c_str(),
    .main_path = main_path.c_str(),
    .packages_path = packages_path.c_str(),
    .icu_data_path = icu_data_path.c_str(),
    .command_line_argc = argc,
    .command_line_argv = argv,
    .platform_message_callback = (FlutterPlatformMessageCallback)OnPlatformMessage
  };
```
but when I focus a TextFormField the OnPlatformMessage method does not get called. When should I be expecting the method to get called? Is there a setting that I am missing?

Many thanks.

**Comment by stuartmorgan** [comment]
Currently you have to run the Flutter event loop on Linux manually in order for platform messages to go through. See:
https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h#L169
and the related code in the in-review https://github.com/google/flutter-desktop-embedding/pull/27

**Comment by billy1380** [comment]
@stuartmorgan perfect, thank you.

**Comment by awdavies** [comment]
Keep in mind this solution is going to be deprecated pretty soon!  I'm also currently working on Text Input, but it's coming along slowly, as I'm hoping I can do it without having to manually implement something to track text state.

**Comment by billy1380** [comment]
This method has proved a little unreliable for me, so I am very excited about the replacement.

I was hoping to register the client id and followed by the properties of the text on selection and then only having to ever track one client id and its properties. What I am seeing is events being skipped e.g. select the text field - nothing happens, move the mouse, the client event triggers (but only sometimes).

There is also another thing that is happening, probably because I am doing something wrong... but when the selected client changes (between two text fields on the screen) the client selected id just keeps growing.

For now I have settled for having simple text input with the cursor being placed at the end of the input text and no selection. Will be really interesting to see how you end up doing it.

**Comment by krisgiesing** [comment]
The macOS text input support ended up needing to implement a text editing model. I'd favor eventually creating a shared editing model that all platforms could use (which came up in a separate discussion about implementation languages).

**Comment by awdavies** [comment]
@billy1380 So the client ID keeps growing, AFAIK, because you're not sending a message back to the engine saying that you've closed the client when it tells you to hide it.  Correct me if I'm misunderstanding, though.

I'm also not aware if it's possible to defocus a client explicitly by, say, clicking on an area outside of the text field (I think this works on Mac because it steals focus from the text client?  I'm unsure as I didn't write it).

But as far as I'm aware, the platform channel opens a new client whenever changing text fields, but before it does this it requests that the previously selected text field (if there is any) be closed.

**Comment by billy1380** [comment]
@awdavies 

You are right about not sending a message back... I will sort that out and see if it fixes the issue with the increasing client ids.

I will post a short clip of the behaviour during selection and see if you can spot what is going on.

Thanks for all the help.

**Comment by billy1380** [comment]
![flutter clicking](https://user-images.githubusercontent.com/1329727/38093068-cbc3ae7a-3361-11e8-8b37-91796504ddd7.gif)

So this is the capture of the "weird" behaviour... I click on the username field, nothing happens, I move the mouse and you see client 1 in the log, then I change focus and an event triggers but it is not the set client event. It recovers later but by still only when the mouse is moved after the click.

The ids are still growing because I have not fixed that, it might be that all this goes away when I provide the callback method, I just thought I should document the behaviour more clearly.

**Comment by billy1380** [comment]
it turns out that the behavior was caused by using glfwWaitEvents, when I switch to glfwPollEvents() it works out... the odd thing now is that even though I am calling the flutter engine back... the client ids are still growing and I am still missing some setClient events.

**Comment by awdavies** [comment]
Do you have a fork that I could look at?  Also have you looked at #27 ?  The plugin framework doesn't look like it'd handle text support very well at the moment, but I haven't looked into it too much this week.

**Comment by awdavies** [comment]
Also that review is just for the file explorer

**Comment by billy1380** [comment]
I looked at #27 that is where I got the clue for the glfwPollEvents... the code is too message and littered with couts at the minute but I will fork and create a branch for you to take a look... will ping you once its done. Thanks again.

**Comment by billy1380** [comment]
Sorry this took so long, but can you take a look at master here https://github.com/billy1380/flutter-desktop-embedding. I am using rapidjson headers in the include folder because I figured it was being imported in the flutter engine build.

Thanks

**Comment by awdavies** [comment]
Thanks for the commit!  Takin a look

**Comment by awdavies** [comment]
Oh man, what a bummer, I've been checking this out on the MacOS embedder, and it seems to me like this is expected behavior AFAICT

**Comment by billy1380** [comment]
:+1: Thank you so much for checking it out.

**Comment by krisgiesing** [comment]
What's expected behavior?

**Comment by awdavies** [comment]
Switching between the text fields over and over causes the client ID to go up monotonically.

**Comment by krisgiesing** [comment]
Right. Yeah, I think that's expected given how the Flutter framework code is written.

**Comment by stuartmorgan** [comment]
Forgot to close this when #46 landed. (It's regressed since, but that's tracked in issue #65).
