### ISSUE TITLE
[flutter/plugins] Support video_player

### ISSUE THREAD

**Issue by Syleron** [google/flutter-desktop-embedding#255]
I realized there has been some work done in integrating video_player plugin support but I only that I can see for macos.

I'd really appreciate if we saw some work done on this for windows as it is a blocking feature for my application. If I can already, perhaps someone can point me in the right direction.

Thanks.

**Comment by stuartmorgan** [comment]
Desktop implementations of video_player are currently blocked on #107 and (assuming you don't want to fork video_player's Dart code to change the codec) #67.

**Comment by tdesc** [comment]
Hello, any news on this topic? Is there any more blockers for moving forward?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/37673 https://github.com/flutter/flutter/issues/41688 and https://github.com/flutter/flutter/issues/39091 have more current status information.

This is remaining open for now because Windows and Linux implementations would be hosted in this repository while the plugin APIs and tooling for those platforms are still volatile.

**Comment by softmarshmallow** [comment]
Its been a while, any updates on this thread?

**Comment by stuartmorgan** [comment]
The plugin APIs for all three desktop platforms are now stable, so implementations for existing plugins would no longer be hosted here.
