### ISSUE TITLE
Support running Android plugins on Linux

### ISSUE THREAD

**Issue by jld3103** [google/flutter-desktop-embedding#264]
Would it be possible to execute the Android plugin code on Linux to avoid rewriting all the plugins for desktop platforms?
Maybe it's possible to use some sort of library exposing the required android interfaces or to use something like Anbox to run the Android code.

I would love to see something like this.

**Comment by stuartmorgan** [comment]
>  to avoid rewriting all the plugins for desktop platforms

One of the primary purposes of Flutter's plugin system is to provide access to native OS functionality; many plugins wouldn't make sense to rewrite for desktop because they don't make sense in that context. Others might make sense in the abstract, but using the Android version would be unlikely to actually work (e.g., embedding a web view).

For cases where this would theoretically work, it would still be a poor solution compared to an actual native plugin. You'd have the overhead of packaging and shipping an entire Android->Linux adapter layer just for a small piece of functionality, and you'd be crossing a JNI boundary twice for every message.

If someone really wants to implement what you are talking about, it could be implemented as a plugin itself that could load Android plugins, or a library that individual plugins could choose to implement a Linux version. It's not something that would be part of this library/Flutter itself.
