### ISSUE TITLE
FlutterMacOS.framework: No such file or directory when running archive from XCode

### ISSUE THREAD

**Issue by gedw99** [google/flutter-desktop-embedding#282]
The standard MacOS example wont Archive making it impossible to Package.

````
PBXCp /Users/apple/Library/Developer/Xcode/DerivedData/ExampleEmbedder-bqhsvtabzizsmagdsrcuhlihrlnh/Build/Intermediates.noindex/ArchiveIntermediates/ExampleEmbedder/Intermediates.noindex/flutter_framework/FlutterMacOS.framework /Users/apple/Library/Developer/Xcode/DerivedData/ExampleEmbedder-bqhsvtabzizsmagdsrcuhlihrlnh/Build/Intermediates.noindex/ArchiveIntermediates/ExampleEmbedder/InstallationBuildProductsLocation/Applications/Example\ Embedder.app/Contents/Frameworks/FlutterMacOS.framework (in target: Example Embedder)
    cd /Users/apple/workspace/flutter/flutter_macos_v0.2.8-beta/flutter-desktop-embedding/example/macos_fde
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude *.tbd -resolve-src-symlinks /Users/apple/Library/Developer/Xcode/DerivedData/ExampleEmbedder-bqhsvtabzizsmagdsrcuhlihrlnh/Build/Intermediates.noindex/ArchiveIntermediates/ExampleEmbedder/Intermediates.noindex/flutter_framework/FlutterMacOS.framework /Users/apple/Library/Developer/Xcode/DerivedData/ExampleEmbedder-bqhsvtabzizsmagdsrcuhlihrlnh/Build/Intermediates.noindex/ArchiveIntermediates/ExampleEmbedder/InstallationBuildProductsLocation/Applications/Example\ Embedder.app/Contents/Frameworks

error: /Users/apple/Library/Developer/Xcode/DerivedData/ExampleEmbedder-bqhsvtabzizsmagdsrcuhlihrlnh/Build/Intermediates.noindex/ArchiveIntermediates/ExampleEmbedder/Intermediates.noindex/flutter_framework/FlutterMacOS.framework: No such file or directory

````

**Comment by stuartmorgan** [comment]
The PR above will fix this, mostly because there may be edge cases other than Archive that will be broken by using OBJROOT. However, to be very clear:
> making it impossible to Package

You should not be doing this.

First, the example isn't intended for packaging or distribution, it's intended for development. Downloading the framework on the fly into a build directory isn't something I would recommend for actual build pipelines; they should fetch it in advance to a known location like any other third-party dependency. It's done that way in the example primarily for ease of development, since we update Flutter frequently, and to minimize confusion (and thus issue/email overhead) from people trying out the example casually who wouldn't necessarily remember to run a script when they updated Flutter.

Second:
> Caveats
> [...] The code and examples here, and the desktop Flutter libraries they use, **are not intended for production use**.
