### ISSUE TITLE
Support geolocator

### ISSUE THREAD

**Issue by allessandrosj** [google/flutter-desktop-embedding#284]
how to use geolocation and internet verification in Windows

**Comment by stuartmorgan** [comment]
One topic per issue please. Retitling for geolocation specifically, and I'll split out another issue for connectivity.

The answer to your question of how to use an existing Flutter plugin on Windows: someone would need to write a Windows implementation of that plugin, using this project's C++ plugin API. Unlike the macOS version, that API isn't stable yet, so it probably doesn't make sense to do that yet unless the plugin maintainers are okay with churn in the implementation; someone could certainly experiment in a fork of an existing plugin though, with the goal of merging back in once it's stable.

**Comment by RazaGR** [comment]
> Unlike the macOS version

can we use geolocator and any other flutter plugin on macOS, or do we have to implement those plugins by C++ plugin API for desktop embedding?

**Comment by stuartmorgan** [comment]
The macOS plugin API is Objective-C, and shares most of its implementation with the iOS plugin API. If the plugin itself only uses APIs that are available on iOS (as a quick look suggests is probably the case for geolocator), adding macOS support should be very straightforward. Plugins that use iOS-specific system APIs, on the other hand, would need entirely new implementations. It's going to depend entirely on the specific plugin.

(In the future FLEPlugin and FLEPluginRegistrar might merge with FlutterPlugin and FlutterPluginRegistrar, at which points there could potentially be some iOS plugins that would work on macOS without code changes.)

**Comment by stuartmorgan** [comment]
I'm going to close this, since implementing plugins that are not part of flutter/plugins (and thus have a clear path to move out of this repository in the future) is out of scope for FDE as the scope has been refined. Desktop platform support should either live in the primary geolocation repository itself, or possibly in a separate repository owned by someone interested in maintaining the desktop implementations of that plugin going forward.
