### ISSUE TITLE
Use-case: Multi-platform using same FDE codebase

### ISSUE THREAD

**Issue by paulreimer** [google/flutter-desktop-embedding#292]
The "sibling" flutter requirement makes multi-platform usage a bit difficult. Ideally I could use the same filesystem (FDE + flutter checkout) for multiple platforms (e.g. running a Windows VM on a macOS host, both FDE apps running at the same time with hot-reload from the same `lib/`).

The main issue appears to be when dart SDK is fetched upon first use of flutter (into sibling `flutter/bin/cache`), that `cache` directory is platform specific. (e.g. macOS cannot use `dart.exe`, Windows cannot run the macOS `dart` executable).

Next issue appears to be that the generated `.packages` file from `flutter build` cannot be used by another filesystem, unless the same paths are present.

These might be underlying Dart issues, or perhaps fde could have an option to select/create separate directories for each platform?

**Comment by paulreimer** [comment]
I'll note that I was able to workaround this by using a separate `flutter channel dev` installation directory on the macOS host, and putting that directory in the macOS PATH. But now I have to keep the dev channel macOS flutter and the sibling flutter (which Windows uses automatically) at the same commit.

If I want to do a full rebuild, I still sometimes have to delete the `cache` directory from sibling flutter before building each platform -- it seems like I do not have full control to say which `flutter` to use.

**Comment by stuartmorgan** [comment]
> The main issue appears to be when dart SDK is fetched upon first use of flutter (into sibling `flutter/bin/cache`), that `cache` directory is platform specific. (e.g. macOS cannot use `dart.exe`, Windows cannot run the macOS `dart` executable).

You could file a feature request in the Flutter project for platform-specific cache directories so that the same Flutter checkout can be shared across platforms; any workaround for that is going to involve having two entire copies of the Flutter tree (which as you note then need to be kept at the same revisions).

> Next issue appears to be that the generated `.packages` file from `flutter build` cannot be used by another filesystem, unless the same paths are present.

This would also be something you'd need to file in the Flutter project; FDE can't control how Flutter's tooling manages dependencies.

> I'll note that I was able to workaround this by using a separate `flutter channel dev` installation directory on the macOS host, and putting that directory in the macOS PATH.

This should not have worked; the version of Flutter being run should always be the one FDE has been pointed to. This is a deliberate design choice; it means that someone experimenting with FDE can still have a `stable` channel Flutter in their path for mobile development, for instance. I'm curious how you determined that adding it to the path made a difference.

> it seems like I do not have full control to say which `flutter` to use.

If you actually want to use one FDE checkout that uses different Flutter trees on different platforms, you should change `tools/flutter_location` and `tools\flutter_location.bat`. All of FDE's tooling uses those scripts to determine the path to Flutter, so changing it there should give you that control.


Closing, since the fundamental obstacles in your workflow are part of Flutter, unrelated to FDE, so there's nothing to track in this project as far as I can tell. If I'm missing something, let me know and I can re-open.

**Comment by paulreimer** [comment]
Alright, off to flutter then!

From what you describe, it sounds like my request for FDE is a parameter to choose the `flutter` binary used by `tools/`, and/or to choose a `flutter_location_config` file (where I would use one file per platform).

Perhaps I've missed another option, maybe using multiple FDE checkouts per platform, and/or moving the app out-of-tree? (I've only tried the `example` app in-tree of FDE)

As to the alternate dev channel `flutter` in my macOS PATH, I meant removing sibling flutter from PATH and adding the other `dev` checkout. That made the `flutter` dart SDK check happy, it didn't get confused when the dart `cache` directory already existed in sibling flutter for a different platform. However, I believe the XCode build process still referenced the `*.dart` SDK files from the sibling flutter, despite my shell using the `dev` flutter.

**Comment by stuartmorgan** [comment]
> my request for FDE is a parameter to choose the `flutter` binary used by `tools/`, and/or to choose a `flutter_location_config` file (where I would use one file per platform).

I'm afraid that supporting a workaround for this very specific edge case isn't worth the complexity of adding yet another layer of Flutter binary control (and I can't think of any other use for such an option). Especially given that it's trivial for someone who really wants this behavior to change `flutter_location` as described above.

> maybe using multiple FDE checkouts per platform, and/or moving the app out-of-tree?

If your app is not in the FDE tree (and that's the expected use case; the example is in-tree only because having it in another repository would make our development more difficult), you could use separate FDE checkouts, yes.

> That made the `flutter` dart SDK check happy [...] However, I believe the XCode build process still referenced the `*.dart` files from the sibling flutter, despite my shell using the `dev` flutter.

What version (if any) of Flutter you have in your path should be irrelevant to FDE; it should never use it. You can use FDE without having Flutter in your path at all. It's not just the dart files, it's the binaries too.

That's why I'm confused by what check would have been affected by you changing your path. Are you referring to `flutter` commands you were running manually?
