### ISSUE TITLE
Ability to remove the Debug Banner 

### ISSUE THREAD

**Issue by msmshazan** [google/flutter-desktop-embedding#305]
Would it be possible to remove the default debug banner showing up when embedding flutter ? If so how ? 
I'm embedding Flutter in windows using SDL2 onto an GLES context using ANGLE
![image](https://user-images.githubusercontent.com/20334207/54089214-98d3a380-438c-11e9-912a-ba4219f2708e.png)

**Comment by franciscojma86** [comment]
You can pass the "--disable-dart-asserts" flag to the engine. Here's the line from the Linux example:

https://github.com/google/flutter-desktop-embedding/blob/master/example/linux_fde/flutter_embedder_example.cc#L63

Hope that helps!

**Comment by msmshazan** [comment]
@franciscojma86 no effect

**Comment by franciscojma86** [comment]
Can you please share the code where you are adding the flag?

**Comment by msmshazan** [comment]
It's something like this 
```c
FlutterProjectArgs args = {};
    char* arguments[] = { "--disable-dart-asserts" };
    args.struct_size = sizeof(FlutterProjectArgs);
    args.assets_path = "flutter_assets/";  
    args.icu_data_path = "artifacts/icudtl.dat";
    args.command_line_argc = 1;
    args.command_line_argv = arguments;
    FlutterEngineResult result = FlutterEngineRun(FLUTTER_ENGINE_VERSION, &config, &args,(void *)&FlutterData, &(FlutterData.Engine));
    ```

**Comment by msmshazan** [comment]
Is this a windows specific issue?

**Comment by stuartmorgan** [comment]
It sounds like you are writing your own embedder from scratch; embedder.cc may be a useful reference for you. For this specific code, see:
https://github.com/google/flutter-desktop-embedding/blob/master/library/common/glfw/embedder.cc#L382
to understand why your code isn't working.

For future reference, if you have issues with the Flutter engine embedding API, the right place to file bugs is the Flutter bug system. I'm not sure why you filed a bug here since you aren't using the code from this project.
