### ISSUE TITLE
[Linux] Error 127

### ISSUE THREAD

**Issue by ttfreeman** [google/flutter-desktop-embedding#315]
I am trying to run flutter on Pixelbook (Linux) and have followed all the steps on this blog : [https://medium.com/@mksl/flutter-dev-on-chromeos-here-and-now-4089d21063f1](url) .  However, I get the following error when trying to run the example:
```
....
Downloading linux-x64 tools… 3.8s
/home/xxxxx/DevLinux/flutter/flutter-desktop-embedding/example/linux_fde/../../tools/gn_dart: line 27: exec: gn: not found
Makefile:122: recipe for target ‘/home/xxxxx/DevLinux/flutter/flutter-desktop-embedding/example/linux_fde/../../out’ failed
make: *** [/home/xxxxx/DevLinux/flutter/flutter-desktop-embedding/example/linux_fde/../../out] Error 127 
```

**Comment by stuartmorgan** [comment]
> I am trying to run flutter on Pixelbook (Linux) and have followed all the steps on this blog : https://medium.com/@mksl/flutter-dev-on-chromeos-here-and-now-4089d21063f1

A blog post someone wrote about using the project is not the authoritative documentation for the project; we have no control over its completeness/accuracy, especially as the project changes over time. The READMEs here have the documentation that we maintain.

> `exec: gn: not found`

In this specific instance, the issue is that the blog doesn't mention [the need to have GN installed](https://github.com/google/flutter-desktop-embedding/blob/master/README.md#setting-up).
