### ISSUE TITLE
Custom Icon and Name for Window Title

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#316]
Add support to Change custom Icon and Title of window from dart code

**Comment by stuartmorgan** [comment]
Window title is definitely something that would be reasonable to add a plugin for (along with the necessary support in the plugin registrar and the GLFW API surface).

What do you mean by "custom icon"?

**Comment by canewsin** [comment]
I Mean Icon that shown before window title and WIndow Bar when App is Opened now there is default App Icon I don't code in C++/C till now but seen API In GFLW to set Custom Icon Since i had nill experience with above languages not able to succeed i tried almost 3-4 hours today after that i will posted the issue here. I changed window title there but felt i should be possible through dart interface i was working on precompiled binaries project people can try using this library without compiling
https://github.com/canewsin/flutter_desktop_launcher
There I see that binaries are compiled with name and icon hard coded within them so we defenately need a plugin for them i prefer glfw interface to do so

**Comment by stuartmorgan** [comment]
Is there a common use case for changing the window icon beyond setting it once when the window is created? I suspect that doesn't rise to the level of something that we would build a plugin hosted here for, rather than just exposing a C API for setting it from the runner (and if someone else wanted to make a plugin to bridge that to Dart, they could certainly do so).

> i was working on precompiled binaries project [...] There I see that binaries are compiled with name and icon hard coded

Precompiled runners have many fundamental limitations—e.g., that as there begins to be an ecosystem of plugins that support desktop, a prebuilt runner won't be able to use them—so it's not a use case we will go out of our way to support. If someone wants to make a prebuilt runner that can change the icon via Dart, they could write and bundle a plugin themselves that does that.

**Comment by canewsin** [comment]
Use case :
 https://github.com/canewsin/flutter_desktop_launcher
 Go to here to better understand the situation
 Here i was providing bins to others so they can use them without compiling from scratch the limitation 
 here is suppose kDefaultTitle is fixed for Flutter string in lib so to change that there is no way with precompiled bins bun if we pass it as flutter create window method we can use that same for icon using GFLWImage && lodepng lib i understood those will work with our use case so we can guide user to put icons in a specific assets folder since we already has ref flutter_assets so we can acheive this
```
GLFWImage decodeOneStep(const char* filename) {
    unsigned error;
    GLFWImage image;

    error = lodepng_decode_32_file(&(image.pixels), &(image.width), &(image.height), filename);
    if (error) printf("error %u: %s\n", error, lodepng_error_text(error));

    return image;
}

//............
GLFWimage icons[1];
icons[0] = decodeOneStep("assets/icons/icon.png");

// window is a GLFWwindow*, 1 is the image count
glfwSetWindowIcon(window, 1, icons);
``` 
LIb used [lodepng](https://lodev.org/lodepng/)

**Comment by canewsin** [comment]
code is from 
https://stackoverflow.com/a/50805586

**Comment by stuartmorgan** [comment]
> Use case :
> https://github.com/canewsin/flutter_desktop_launcher
> Go to here to better understand the situation

See my second paragraph; this is not a use case that this project will be writing plugins to support.

I'm happy to accept a patch that adds the necessary C API to set the icon, since that's useful to anyone writing a runner; if you then want to bridge that API to Dart via a method channel in your own runner, you could certainly do so.

**Comment by canewsin** [comment]
The problem is i don't know how to code in c/c++ i almost tried but failed if you help me i will submit in a 15 minutes

**Comment by canewsin** [comment]
The problem while building is i copied above method to embedder.cc file 
GLFWImage is not recognized as type in Visual Studio 2017
also lodepng includes are not recognized i was pointing header files to vs 2017

**Comment by stuartmorgan** [comment]
The title is now exposed in the C API, rather than being hard-coded in the embedder. Being able to set it from the Dart side is moved to https://github.com/flutter/flutter/issues/30712, which I expect to implement shortly.

There's also now a C API for setting the icon from raw pixel data (passing through directly to the GLFW API). If you want to support loading the image from a file, and/or setting it from the Flutter side via a method channel, that will be up to you to provide in your runner.

**Comment by extrovert-codev** [comment]
For the title:
Go to windows > runner > main.cpp folder, find a " !window.CreateAndShow(L"schedule_task", origin, size) " And change the "schedule_task" text

For the icon:
Go to windows > runner
1. You can changes or replace icon in resources folder
2. Open file Runner.rc > find " IDI_APP_ICON ", and changes "app_icon.ico" from resources

**Comment by stuartmorgan** [comment]
@extrovert-codev This is a very old issue that was filed when the Windows embedding was completely different. Nothing here is relevant to the current desktop support in Flutter, and hadn't been for at least a year.
