### ISSUE TITLE
CSD support?

### ISSUE THREAD

**Issue by refi64** [google/flutter-desktop-embedding#340]
It would be great if this project supported CSDs. Something to the effect of: 

```dart
import 'package:csd/csd.dart';

//... 
Csd.enableIfPossible(); // inside main()
// inside a build function
AppBar(
  actions: [
    if (Csd.enabled)
      MyCloseButton(),
  ]
)
``` 

I'd be happy to contribute to this as needed, though it [mostly depends on some upstream GLIDE work](https://github.com/glfw/glfw/pull/1420).

**Comment by stuartmorgan** [comment]
I assume CSD in this context is https://en.wikipedia.org/wiki/Client-Side_Decoration?

That would be part of the desktop shell itself, rather than this project, so please file this the Flutter issue tracker (I can't move this across repos, unfortunately). If you reference it here after filing, I can make sure to add the right labels to the bug there.

**Comment by refi64** [comment]
Ah sorry I didn't realize the sources had moved over there, I just filed https://github.com/flutter/flutter/issues/31373.
