### ISSUE TITLE
[Linux] FileChooserType.save doesn't append selected file extension to filename

### ISSUE THREAD

**Issue by mtcliatt** [google/flutter-desktop-embedding#368]
When using the [`FileChooser`](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_chooser) plugin on Mac and specifying one accepted file type, you can save a file with the name `file.json` by entering the name `file`. On Linux, the same configuration doesn't automatically append the `.json` extension.

On Mac, the file dialog doesn't show an option for the file extension. On Linux, the only accepted file type is shown and selected in a dropdown menu in the bottom right. Even with the file type selected, the path returned from invoking the native `FileChooser.Show.Save` is the filename without the appended extension.

I'm not actually sure if this is a bug or the right bug though, because the description of `FileChooserChannelController` indicates it's specific to macOS. There doesn't seem to be an equivalent controller for other platforms though.

**Comment by stuartmorgan** [comment]
macOS automatically appends the extension in that case; it's a built-in behavior. Apparently GTK's file chooser doesn't do the same thing. It does, in my testing, auto-select the portion of the selected filename before the extension when showing the dialog though, meaning a user has to go out of their way to save a file with no extension (assuming the suggested filename has it, which it should if the app is trying to steer the user in that direction).

Given that this is a difference in the standard behavior of the platform control, I wouldn't consider this a bug. If a specific client really wants this behavior even on Linux where it would (AFAICT) be unexpected to the user, they can easily check whether the returned value has an extension and add one if not. Closing based on that; if you feel strongly that this is not the correct behavior on Linux, examples of Linux software that behave like otherwise would be helpful.

> the description of FileChooserChannelController indicates it's specific to macOS.

That's just an outdated comment from the initial implementation that was macOS-only.

**Comment by mtcliatt** [comment]
Thanks Stuart, that makes sense. 

I think behavior as I've tested it feels odd because I'm creating a new file, so the text field for the filename is initially empty (an alternative is to populate the filename with a sample name (e.g. 'NewProject.json') and automatically select the portion before the file extension).

But I'm not sure what the expected behavior would be if a user typed in the wrong file extension. In my case, I had to go out of my way to add the file extension (since I was creating a new file), and the selector didn't actually do anything. This of course can be easily solved in my case with your suggestion of checking the return value. But, how should I handle this if the return value indicates the user typed `file.png` but selected `*.jpg`?

**Comment by stuartmorgan** [comment]
> an alternative is to populate the filename with a sample name

This is what I would expect/recommend, certainly. See the `testbed` application, for example, which does that.

> But, how should I handle this if the return value indicates the user typed file.png but selected *.jpg?

This seems like something that's entirely up to your application. If you are confident that you know more about what the filename should be than the user, you could change the extension, or append the extension anyway (file.png.jpg).
