### ISSUE TITLE
[flutter/plugins] Support firebase plugins

### ISSUE THREAD

**Issue by canewsin** [google/flutter-desktop-embedding#431]
Firebase Team Released C++ SDK for Desktop side currently in beta could some make any plugin with this sdk so there is plugin for desktop side

**Comment by stuartmorgan** [comment]
> Firebase Team Released C++ SDK for Desktop side currently in beta

Please provide a link. The only C++ SDK I'm aware of specifically says that it's for development use in testing mobile games on desktop, and not for actually shipping in desktop software.

**Comment by canewsin** [comment]
Why not currently there is no native way to implement firebase features in desktop though we have dart firebase unofficial sdk there is no support for real-time updates since its based web-sockets if we take c++ sdk it gives ability to do real-time updates and apps that are solely depends on firebase are happy to run on desktop, firebase helps most of developers to avoid database maintenance for most apps
If we have another alternative we may ignore those sdk but leaving it to user may decide whether he use he use it stable environment My opinion is he will ultimately use those because those is no alternative to those sdk and it also helps in ffi merge to dart sdk once its released we can completely eliminate both android and ios side native implementations and completely rely on those c++ sdk 
What i expect is we have to convert java code to c++ code without changing channel names and method names in official firebase method implementation so that one don't have write two methods to do something on two or more platforms

**Comment by stuartmorgan** [comment]
I gather from your response that you are talking about the SDK I referenced.

This will be documented in a README soon, but briefly: the bugs marked [flutter/plugins] exist because hosting plugins for desktop platforms with plugin APIs that aren't at all stable yet in the flutter/plugin repository wouldn't make sense, but there are a number of plugins that could relatively easily be built now, hosted temporarily in FDE where API instability is expected, and then moved once the API is stable.

What you are proposing has no migration path into flutter/plugins, so will not be built here.
