### ISSUE TITLE
How to run debug mode with flutter desktop

### ISSUE THREAD

**Issue by mofada** [google/flutter-desktop-embedding#438]
My flutter desktop can run normally, but how do I debug in android studio? I still have a question, how to export exe files running on windows? Thank you

**Comment by stuartmorgan** [comment]
Android Studio doesn't yet fully support desktop. What's [in the README]() is all we can suggest at this point about using Android Studio to run desktop projects. It may also be possible to attach to an arbitrary Flutter process by observatory URL, but that would be something to check Android Studio docs or support forums for information about.

In the future, please use the mailing list for questions rather than the issue tracker, as requested in the README.
