### ISSUE TITLE
What files should be deployed to run on other windows machines?

### ISSUE THREAD

**Issue by diegomgarcia** [google/flutter-desktop-embedding#466]
Hi guys, 

I was trying to deploy to another windows machine but I was getting errors from missing dlls related to visual studio runtime, I've installed those but as mentioned in the readme it's asking from the debug version, so with that in mind I began to copy individual dlls as the errors where popping, but after fix the ones that was showing I'm getting the famous 0x0000007b error when launching. 

So can you guys guide me on whats the correct files to deploy ?

Regards,
Diego Garcia

**Comment by stuartmorgan** [comment]
In the future please use the mailing list, not the issue tracker, for questions, per the project README.

> it's asking from the debug version

The Flutter library uses a statically linked runtime, so if your application is trying to load debug runtime DLLs it sounds like you built the runner in debug mode rather than release mode. I would suggest doing the later if you are going to try to run on another machine. You could also locally change the runner build to statically link the runtime. If you want to keep using the dynamic runtime you should try asking in a generic Windows development forum about what DLLs you need to package with it--distribution of Windows builds isn't something we've looked at yet at all, so I can't tell you what the complete list is. (I suspect we will switch to `/MT` at that stage, but it'll need evaluation.)

Specifically to Flutter, you need to copy everything in the build output directory: the Flutter DLL, the `data` directory, and any plugin DLLs.

**Comment by diegomgarcia** [comment]
Hi @stuartmorgan sorry about that, I didn't saw the readme about the questions ... 

Thanks for your clarification I was copying the files from debug  that was the problem, just do a flutter build windows and copy the release files to the destination machine and it works as expected.
