### ISSUE TITLE
How to work with Auto Update for flutter desktop app.

### ISSUE THREAD

**Issue by richard457** [google/flutter-desktop-embedding#469]
**Describe Request**
I want to provide auto update to flutter desktop application how can I achieve that?

**Comment by stuartmorgan** [comment]
Auto-update is beyond the scope of this project. There are a variety of ways of providing updates to desktop applications, depending on the platform(s) you are interested in; any of those should work for a desktop application built with Flutter just as they would for a desktop application built with other technologies.

**Comment by richard457** [comment]
@stuartmorgan I understand it is not in scope now, don't you think is something needed though? for example something like this https://electronjs.org/docs/api/auto-updater

**Comment by stuartmorgan** [comment]
I think many people will want to be able to update desktop apps built with Flutter, just as many people want to be able to update desktop apps built directly using the OS toolkits. But that doesn't mean that Flutter needs to incorporate an auto-updater, just as AppKit and Win32 don't have auto-updaters.

Just as someone writing an app directly using AppKit or Win32 has a variety of options for handling updates (including situations where they won't want to incorporate one at all, such as distribution through the macOS app store), Flutter developers have all those same options. I would expect that people will likely develop plugins for some of the more popular ones to make integration even easier.

**Comment by richard457** [comment]
I am ready to build this plugin, I need your support, I don't know why this has no weight it should have in 2019 auto-update is a must for every app. Please let me know how I can give my help. @stuartmorgan

**Comment by stuartmorgan** [comment]
> I am ready to build this plugin, I need your support

I'm happy to answer specific questions about desktop plugin development on the mailing list or StackOverflow.

**Comment by sgehrman** [comment]
I want this too.

**Comment by csells** [comment]
We're working now to add command line argument support, which will enable you to use auto-update frameworks like Sparkle.

**Comment by richard457** [comment]
I am glad this is getting the attention it deserves, will be happy to be involved and contribute

**Comment by stuartmorgan** [comment]
> I am glad this is getting the attention it deserves

I think you misunderstood Chris's response; nothing about my earlier comments has changed. He's referring to a specific piece of functionality that may or may not be relevant to someone writing an auto-update plugin (depending on exactly how it's written). It's still up to the community to write those plugins.

> will be happy to be involved and contribute

See my comments above; it's been possible to write plugins for at least a year, so anyone who wants to write such a plugin has been, and continues to be, free to do so. You indicated at that time that you wanted to start on one; if you did and encountered missing functionality that blocked you, you should definitely file a bug (in the Flutter repository), as that's the only way for us to know that you are blocked.

Since FDE no longer includes the framework or the plugin APIs, this request is no longer relevant to this repository at all, so I'm going to lock this.
