### ISSUE TITLE
Collaborating

### ISSUE THREAD

**Issue by gedw99** [google/flutter-desktop-embedding#5]
This is great.

Whats the thoughts on Flutter plugins ? For example the Webview.

**Comment by stuartmorgan** [comment]
FLEViewController allows registering arbitrary FLEPlugins, which wraps platform channels, so client code can register arbitrary platform channels of their own. There are a few already in the codebase, and more will follow, although the Dart side still needs to be added to show the other half of implementing one.

Closing since there's no specific issue to track here. (Since there seems to be enough interest in this project to warrant it, I'll set up a mailing list on Monday for non-issue questions and discussions like this, and update the project page and flutter-dev thread with that information.)

**Comment by zoechi** [comment]
Where do/did you create the mailing list?

**Comment by xqwzts** [comment]
Here it is: https://groups.google.com/forum/#!forum/flutter-desktop-embedding-dev
