### ISSUE TITLE
Raspberry Pi linux

### ISSUE THREAD

**Issue by captnPlanet** [google/flutter-desktop-embedding#52]
Would it be possible to use the linux embedder in a Raspberry Pi?

**Comment by stuartmorgan** [comment]
(In the future please use the mailing list, rather than the issue tracker, for general questions/discussion.)

Raspberry Pi is not within the scope of this project, so if you're interesting in writing a Flutter embedder that runs on Raspberry Pi that would be something to host separately. I have no idea if the current Linux implementation would work for you, but if it does you could certainly start from a fork.

**Comment by gedw99** [comment]
Just use Android things.
I got a few apps working on it when deploying over adb.
In the CLI they call the device target IOT, as opposed to Android and iOS.

Android things is supported on the RPI3 I believe.

I could not pull off a deployment to the Android Things play store
equivalent yet. I put an issue in the main flutter repo and it's still
open. But I think the team is on it but that's all I know so far...

**Comment by carnivorePaul** [comment]
There's a few reasons why android things will not suffice:
1. It takes over 30 seconds to boot to app
2. Hardware acceleration does not work with flutter and you get at most 5fps.

**Comment by awdavies** [comment]
Off the top of my head (haven't done any specific research into this), it _should_ be possible with the Raspbian distribution given you have the required dependencies specified in the README.  However those dependencies were derived on an Ubuntu workstation using an amd64 arch, so I'm not sure what versions of everything are available Raspbian given it's running ARM.

Currently there isn't a .deb available for the embedder as a library, though, so you'd still have to go through the process of building everything on the device.  The biggest question-mark for me at the moment is a) how the flutter engine will compile for ARM, and b) what the dev libraries on Raspbian look like.

**Comment by carnivorePaul** [comment]
Interesting, so there's a chance, by running through all the steps on a raspberry pi, we could get this to work...

**Comment by gedw99** [comment]
Regarding Android things here is the issue

https://github.com/flutter/flutter/issues/17173#issuecomment-387391020

It's great for certain things and GPU acceleration will hopefully be fixed.
It's slow on my tests too :(

Regarding rasp pi without Android things. Is also another great option.
But in a real work iot situation aren't you going to need transactional AB
OS upgrades ?
That's the clinger for real world usage.

**Comment by awdavies** [comment]
> Interesting, so there's a chance, by running through all the steps on a raspberry pi, we could get this to work...

Right.  It's worth giving it a spin, at least.  Just don't get your hopes too high :wink:

**Comment by stuartmorgan** [comment]
Again, none of this is in scope for this project. If you want to have a discussion about using Flutter on Raspberry Pi and/or Android Things, please find a relevant forum to continue the conversation.

**Comment by carnivorePaul** [comment]
> Currently only macOS is supported, but the goal is to support **other desktop embedders in the future**.

Does this not fall under **other desktop embedders**?

**Comment by stuartmorgan** [comment]
> Does this not fall under other desktop embedders?

That was meant to refer to Linux and Windows. I'll update it to be explicit about that (especially since it's out of date about what's currently supported!)

> Rpi is arguably the worlds best selling computer

Android and iOS devices are also very popular computing devices as well, but that doesn't make them desktops. This project has a specific scope; it's not meant to cover every computing platform that Flutter itself doesn't support.

> there should be some serious incentive to get this working.

I'm not trying to discourage you from getting it working if that's something you are interested in doing. I'm just saying that it's not within this project's scope (in much the same way that this is a separate project from Flutter because desktop embedding is not currently within the scope that Flutter is focused on).

**Comment by gedw99** [comment]
Well i guess we have to wait to see what the Flutter CLI of "flutter built iot" really means ?
