### ISSUE TITLE
How to use SQLite?

### ISSUE THREAD

**Issue by AppleEducate** [google/flutter-desktop-embedding#554]
I have an example project: https://github.com/AppleEducate/moor_shared

Currently uses SQlite on mobile, web and desktop.

I am curious if i am missing something simple. How do i link a path to sqlite on desktop? https://github.com/simolus3/moor/issues/76

Does macos, windows and linux have sqlite on the operating system already or do i need to bundle it?

**Comment by simolus3** [comment]
MacOS definitely has sqlite available as a shared library. The error code returned from sqlite here is 14 (`SQLITE_CANTOPEN `). Maybe that is because of some permission problems?

**Comment by AppleEducate** [comment]
OK cool, i thought macos did too.

It could be of how macos sandboxes the app, but i would think this path would still work.

**Comment by simolus3** [comment]
@AppleEducate I managed to get your code working by using a file that would be stored in 'Library/Containers/$appId/Data'
```dart
// put this in lib/data/database/mobile.dart
if (Platform.isMacOS || Platform.isLinux) {
    final file = File('db.sqlite');
    return Database(VMDatabase(file, logStatements: logStatements));
}
```

I think it failed to open a database in `/tmp/db.sqlite` because Mac apps aren't allowed to access the global file system (??). And I think the reason it didn't work with your original code is that you're implicitly using `Directory.toString` [here](https://github.com/AppleEducate/moor_shared/blob/4d4d2b8d3cb7c34690d55c93b430649dc726c68e/lib/data/database/database/mobile.dart#L15), which doesn't return a valid path. I don't have enough experience with MacOS development to give a definite answer unfortunately.

**Comment by AppleEducate** [comment]
ok no worries, thank you! I will update my example. I don't have much experience either with MacOS but we have a client that wants one.

**Comment by AppleEducate** [comment]
That worked!!

**Comment by stuartmorgan** [comment]
> I think it failed to open a database in /tmp/db.sqlite because Mac apps aren't allowed to access the global file system (??).

The macOS App Sandbox, which the example project is configured to use by default, does not allow arbitrary filesystem access.
