### ISSUE TITLE
MacOs hide titlebar

### ISSUE THREAD

**Issue by vanlooverenkoen** [google/flutter-desktop-embedding#571]
How can I hide the titlebar of the macOS. and use custom close, minimize, maximize buttons.

Current situation
![image](https://user-images.githubusercontent.com/21172855/65423549-9a852600-de09-11e9-9e5e-9d7baf62bb66.png)

The ultimate sollution:
![image](https://user-images.githubusercontent.com/21172855/65423620-caccc480-de09-11e9-9a51-886d02d7ae3e.png)

**Comment by stuartmorgan** [comment]
Please use the mailing list, not the issue tracker, for questions.

If you want a non-standard window you need to alter its properties in the XIB, and/or add code to MainFlutterWindow.swift. There's nothing Flutter-specific about the window, so it would be the same process as doing it in a non-Flutter project.

**Comment by guidezpl** [comment]
Echoing Stuart's comment. Though, since this took me a bit of time to figure out, I'll add that 4 options need to be selected in `MainFlutterWindow.swift`. 

<img width="255" alt="Screenshot 2020-05-07 at 13 08 56" src="https://user-images.githubusercontent.com/6655696/81288072-35163a80-9064-11ea-966c-1749e45670a4.png">

Result:
<img width="609" alt="Screenshot 2020-05-07 at 13 09 05" src="https://user-images.githubusercontent.com/6655696/81288115-46f7dd80-9064-11ea-8518-08026f65df47.png">

**Comment by silverhairs** [comment]
Is there a way of doing this on Linux ?
