### ISSUE TITLE
[macOS]: failed to launch from VSCode: ArgumentError - invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by guiguan** [google/flutter-desktop-embedding#586]
I got this error when I was trying to launch `macOS` from VSCode:

```
Launching lib/main.dart on macOS in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    ### Command
    ```
    /usr/local/Cellar/cocoapods/1.8.1/libexec/bin/pod install --verbose

   ...

   ArgumentError - invalid byte sequence in US-ASCII

   ...

    [!] Oh no, an error occurred.
    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues
    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new
    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
    Don't forget to anonymize any private data!
    Looking for related issues on cocoapods/cocoapods...
     - Pod Install failed
       https://github.com/CocoaPods/CocoaPods/issues/9222 [open] [1 comment]
       14 hours ago
     - Error while setting up CocoaPods
       https://github.com/CocoaPods/CocoaPods/issues/5979 [closed] [23 comments]
       06 Dec 2018
     - invalid byte sequence in US-ASCII
       https://github.com/CocoaPods/CocoaPods/issues/1036 [closed] [9 comments]
       08 Jun 2017
    and 15 more at:
    https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
```

I have `export LANG=en_US.UTF-8` in my `~/.profile` and have also configured VSCode as:

```js
{
  "dart.env": {
    "LANG": "en-US.UTF-8",
  }
}
```

However, directly launch from terminal works:

```shell
flutter run -d macOS
```

My other targets `web`, `ios` and `android` work from VSCode.

**Comment by stuartmorgan** [comment]
If it works in terminal but not VS Code you'll need to file this in the Dart Code issue tracker.

**Comment by DanTup** [comment]
I hit this issue myself today, so ended up doing some more digging. Some notes in case others stumble across this.

As far as I can tell, the root cause seems to be that Ruby uses the `LANG` env variable to decide the default file encoding when reading files. If it's not set, it uses ANSII. CocoaPods therefore advises setting LANG to something UTF-8.

On macOS, the terminal sets `LANG` for you, so running from a terminal gets a reasonable `LANG` env variable that's likely UTF-8 and everything is fine. For processes launched outside of the terminal (for ex the dock), this is not set.

So I wanted to try and set `LANG` when spawning Flutter. However from nodejs (where VS Code extensions run in), the only way to get at the system locale that I can find does not work from the extension host (https://github.com/microsoft/vscode/issues/85675). Forcing `en_US.UTF-8` for all Flutter processes is risky because it could change the behaviour of far more than CocoaPods.

So, I think there are several potential fixes... in order of what seems most sensible to me:

- Could CocoaPods explicitly set encoding when reading files instead of relying on Ruby defaults? (I've asked this question at https://github.com/CocoaPods/CocoaPods/issues/9347#issuecomment-559069320)
- Flutter explicitly sets `LANG` to `en_US.UTF-8` (or `${Platform.localeName}.UTF-8` if available) when spawning CocoaPods
- In VS Code we set `LANG` if it's not already set (setting to `en_US.UTF-8` is more risky here than Flutter doing it only for CocoaPods, so we should probably only do this if we can get access to the system locale via https://github.com/microsoft/vscode/issues/85675)
- The user can use `dart.env` to set `LANG` explicitly (this kinda sucks, because it relies on the user hitting a problem, understanding it, and successfully finding the correct fix)

**Comment by DanTup** [comment]
Flutter now forces `LANG` when spawning CocoaPods (https://github.com/flutter/flutter/pull/45710), so this should be fixed everywhere now :-)
