### ISSUE TITLE
On a phone the example shows a window that goes out of the display.

### ISSUE THREAD

**Issue by programmin1** [google/flutter-desktop-embedding#590]
**Describe the bug**
When I build and run on the Librem 5 phone emulator, the example doesn't work because the + button is to the right of the screen. The width and height are hardcoded in the main.cc file, and they should be the full device width and height when the user is on a Linux-based phone. I'm not sure how you get that in C/Dart. I have a writeup on how I ran this and what it looks like currently, on this post: https://howtotrainyourrobot.com/flutter-to-librem-5-phone/

This seems like an important bug as there are going to be more and more Librem5 users as their new phone builds are released, and they will be wanting their Flutter-based apps!

Thank you for your work thus far in making this work and compile cross-platform :)

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel master, v1.10.15-pre.93, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.93 at ~/mydevtools/flutter
    • Framework revision 3fea2838df (27 hours ago), 2019-10-11 16:18:00 -0700
    • Engine revision eed171ff35
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 965b8cb1d8)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = ~/tools/android/android-studio
      but Android SDK not found at this location.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 3.8.0
    • GNU Make 4.1

[!] Android Studio (version 3.5)
    • Android Studio at ~/tools/android/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version openjdk version "1.8.0_202-release"

[✓] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

```

**Comment by stuartmorgan** [comment]
> The width and height are hardcoded in the main.cc file

That's because, as explained [here](https://github.com/google/flutter-desktop-embedding/blob/master/example/App-Customization.md#linux), no customization support has been added to Linux yet.

> they should be the full device width and height when the user is on a Linux-based phone

Someone could certainly customize their copy of the Runner to do that. There are no plans to support complex sizing logic in the default example, especially for the specific case of phones when the focus of this project is desktop.

The window_size plugin in this repository also supports Linux, so someone could easy put Dart-side logic in their application to fit to the screen using that plugin until such time as there's built-in support for window size control.

I'm going to close this as making the example here work well on a phone by default is not a goal for the project, and there are multiple solutions someone who wants to targets phones could use to address this locally in their project.

**Comment by stuartmorgan** [comment]
As an aside, from your link:

> When unzipped you should add the following to ~/.bashrc so you have the command available always:
>
> export ENABLE_FLUTTER_DESKTOP=true

If you are going to write up your own copy of the setup instructions, it would be better to use the current instructions, rather than instructions that were obsoleted months ago. (Even better would be to simply link to [the official instructions](http://flutter.dev/desktop#tooling) so that as they change people won't be getting incorrect information.)

**Comment by programmin1** [comment]
Linked, thanks. I would hope that the default examples _could_ be mobile responsive in the future. Thank you for the suggestions to remedy this.

**Comment by stuartmorgan** [comment]
> I would hope that the default examples could be mobile responsive in the future.

It's theoretically possible, but there is still a very substantial amount of work to do for desktop--which, again, is what this project is targeting.

> This seems like an important bug as there are going to be more and more Librem5 users as their new phone builds are released, and they will be wanting their Flutter-based apps!

It's important to consider relative scale here; desktop has an install base that's over a billion active machines; Librem 5 hasn't even reached the stage of mass-produced cases yet.

If this effort is useful to people trying to develop apps for Linux phones that's great, but we have no plans to divert efforts away from the (again, significant) remaining desktop work to optimize for that use case. If anyone in the community is particularly interested in streamlining that, I would recommend maintaining a fork of the Runner that's optimized for it, or a plugin that resizes the window on registration.

Although it's also worth noting that the Linux desktop embedding is, as noted in the documentation, nowhere near production-ready, so there are much more important things to focus on than initial window size even for that use case.
