### ISSUE TITLE
mac clean local data

### ISSUE THREAD

**Issue by 926** [google/flutter-desktop-embedding#610]
Hi,
Thanks for making an amazing solution to build desktop app,
We use Sembast to store data locally, and encountered the following issue : 

While testing on android, if we change the db, we need to either : 

- delete the android app and rebuild / run debug
- go into setting/app/ and delete data

Now pardon me if this is obvious but I do see how to do this while testing on mac desktop.
I dismantled the db and cannot even load the app to create a deleteAll function

Thank you for your help

**Comment by stuartmorgan** [comment]
The application is running on your machine, under your user account, so you can just manually delete the file from your filesystem (at whatever path you used for it in your code).

**Comment by 926** [comment]
Thank you for your quick feedback.
Here is what I see in the folder,
![image](https://user-images.githubusercontent.com/14161798/69411457-503afb00-0d0d-11ea-8b20-06fd0da3f511.png)

This is in the Debug,
But it seems that it keeps starting using previous local db.
Could you please confirm that deleting this file while reset the whole ?

Thanks again

**Comment by stuartmorgan** [comment]
> Could you please confirm that deleting this file while reset the whole ?

That would be true only if your code is storing data relative to the application's location, which would be a very strange place to store user data.

I can't tell you what you need to delete because I don't know what location you are using when you store data. Only you know what paths you are using in your code. Whatever location you have chosen to write data to, that's what you need to delete in order to delete that data.

**Comment by 926** [comment]
Found it, the data (using sembast ) was stored as 'demo.db',
This is the exact path on my laptop : 
/Users/mac/Library/Containers/com.weebi.yobi/Data/Documents

Deleting the database allowed me to debug without any problem,
Thank you for your support and best of luck in developing flutter desktop further,
Truly amazing
