### ISSUE TITLE
[Linux] Provide app icon, or documentation on how to create an app icon

### ISSUE THREAD

**Issue by gary-c-chang** [google/flutter-desktop-embedding#630]
**Describe Request**
MacOS and Windows have app icon artifacts in this repo already so it's easy to figure out how to customise the app icon for those desktops, but it took me quite some searching to figure out how to do it for linux. Consider adding some doco eg. refer to https://www.maketecheasier.com/create-desktop-file-linux/  etc. and provide an example .desktop file with instructions to say copy to ~/.local/share/applications. Better still is if an automated way could be provided to set all this up via an enhancement to Makefile.

**Comment by stuartmorgan** [comment]
On macOS and Windows, icons are part of the application itself, and thus part of the build process. A `.desktop` file is, as I understand it, something that would be made by an installer given that it's referencing the executable and icon by path and must be placed in a specific location in the system; it seems more analogous to a desktop/menu/dock shortcut on macOS or Windows than to the icons that are part of the application on those platforms.

> Consider adding some doco eg. refer to https://www.maketecheasier.com/create-desktop-file-linux/ etc. and provide an example .desktop file with instructions to say copy to ~/.local/share/applications

That article and your suggestion are things that would be done at install time, not build time; installers are not in scope for this repository, so it's not something I plan to document here.

> Better still is if an automated way could be provided to set all this up via an enhancement to Makefile.

It's not clear to me how that would work; can you provide an example of how one would make a `.desktop` file in the context of a build step, rather than an installer?

**Comment by stuartmorgan** [comment]
Absent an explanation of how this would be done other than an installer, closing as out of scope for this project.
