### ISSUE TITLE
Enhance example to shows basic responsive screens

### ISSUE THREAD

**Issue by gary-c-chang** [google/flutter-desktop-embedding#631]
**Describe Request**
The examples currently show the same screen across the different targets regardless of window size and the user resizing the app window. Consider enhancing these examples to have responsive screens eg. show a list and detail screen side by side if the window is large enough, then reverting to separate list / detail screens when the window is small, possibly using LayoutBuilder to detect the current window size. This will also emphasize the difference between static screen sized apps for mobile devices and resizable apps on desktops from a single codebase, showcasing another simple-to-use yet powerful feature of Flutter.

**Comment by stuartmorgan** [comment]
This repository deliberately has a narrow scope; providing rich examples is not within that scope. `example` is, by design, the standard Flutter template app with the minimal changes necessary to run on desktop platforms.

If you would like to see official examples of responsive design, that would be a feature request for https://github.com/flutter/samples
