### ISSUE TITLE
fatal error: 'url_launcher_plugin.h' file not found #include <url_launcher_plugin.h>

### ISSUE THREAD

**Issue by hariom-dev** [google/flutter-desktop-embedding#666]
flutter/generated_plugin_registrant.cc:7:10: fatal error: 'url_launcher_plugin.h' file not found
#include <url_launcher_plugin.h>

**Comment by stuartmorgan** [comment]
In the future, please fill out the bug template, or at least provide basic information like what platform you are on and what steps you took, rather than just an error message with no context.

This error means that you didn't correctly follow [the steps for integrating a Windows or Linux plugin into your build](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#using-plugins). Since you didn't provide any information about what you did I can't be more specific, but if you are still having problems please explain in detail what steps you performed.

Closing as this is almost certainly a configuration error, rather than a bug.

**Comment by hariom-dev** [comment]
i'm using Linux

**Comment by stuartmorgan** [comment]
Since you didn't describe any Makefile changes in the duplicate you filed, my answer is the same: you need to read the instructions linked above to integrate the plugin into your build. Specifically, for Linux, [this section](https://github.com/google/flutter-desktop-embedding/tree/master/plugins#adding-to-your-application).

**Comment by stuartmorgan** [comment]
FYI, an change that was in progress to change the way plugins are referenced just landed, so if you're still working on this I recommend updating to master; the Makefile changes are much simpler now, and the instructions have been updated accordingly.
