### ISSUE TITLE
Check failed: gl_version_string

### ISSUE THREAD

**Issue by toy-lin** [google/flutter-desktop-embedding#678]
When i run the example, the fatal error occurs every time.

> PS E:\git\flutter-desktop-embedding\example> flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(107)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[FATAL:c:\b\s\w\ir\cache\builder\src\flutter\shell\gpu\gpu_surface_gl_delegate.cc(48)] Check failed: gl_version_string.
The GL proc resolver's glGetString(GL_VERSION) failed
Syncing files to device Windows...
Lost connection to device.

**Flutter doctor**:
>PS E:\git\flutter-desktop-embedding\example> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel master, v1.15.4-pre.97, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 23.0.3)
    X Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "D:\E\Android\sdk\tools\bin\sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[âˆš] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.2)
[!] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[âˆš] Connected device (1 available)
! Doctor found issues in 2 categories.

**Comment by stuartmorgan** [comment]
You'll need to file this issue in [the Flutter issue tracker](https://github.com/flutter/flutter/issues), since the code in question is part of the Flutter engine, not the runner that lives in this repository.

Once it's filed leave a comment here referencing that issue, and I'll make sure it gets the right labels.

(It would be good if you could try running this under the Visual Studio debugger to see if there is any more logging, since it looks like some of the higher level logging is using `OutputDebugString` rather than console logging.)

**Comment by toy-lin** [comment]
This issue references to [here](https://github.com/flutter/flutter/issues/51286).
