### ISSUE TITLE
"\Windows was unexpected at this time" building on Windows

### ISSUE THREAD

**Issue by fer9917** [google/flutter-desktop-embedding#687]
I have updated flutter on the master channel with "flutter upgrade" and it sends an error when trying to run the application in windows.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.241, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.5)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)

• No issues found!

$ flutter run --verbose -d windows -v
[ +55 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +1 ms] 1d3fcfd6ca7e83c6c7d134fc99deb015839b0389
[ ] executing: [C:\src\flutter/] git describe --match v*.. --first-parent --long --tags
[ +95 ms] Exit code 0 from: git describe --match v*.. --first-parent --long --tags
[ ] v1.15.3-241-g1d3fcfd6c
[ +14 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ ] origin/master
[ ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +43 ms] Exit code 0 from: git ls-remote --get-url origin
[ ] https://github.com/flutter/flutter.git
[ +191 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +119 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ ] master
[ +132 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +44 ms] executing: C:\Users\fernando.delacruz\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +57 ms] Exit code 0 from: C:\Users\fernando.delacruz\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ ] List of devices attached
[ +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +10 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +503 ms] Launching lib\main.dart on Windows in debug mode...
[ +17 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\FERNAN~1.DEL\AppData\Local\Temp\flutter_tool.ceed929a-5c91-11ea-9f56-a4db30d23473\app.dill --packages C:\Users\fernando.delacruz\Downloads\PCH\flutter-desktop-embedding\example.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[ +53 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[ +59 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[ ] [
{
"instanceId": "fd954ded",
"installDate": "2020-02-21T17:50:40Z",
"installationName": "VisualStudio/16.4.5+29806.167",
"installationPath": "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise",
"installationVersion": "16.4.29806.167",
"productId": "Microsoft.VisualStudio.Product.Enterprise",
"productPath": "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe",
"state": 4294967295,
"isComplete": true,
"isLaunchable": true,
"isPrerelease": false,
"isRebootRequired": false,
"displayName": "Visual Studio Enterprise 2019",
"description": "Scalable, end-to-end solution for teams of any size",
"channelId": "VisualStudio.16.Release",
"channelUri": "https://aka.ms/vs/16/release/channel",
"enginePath": "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service",
"releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.5",
"thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
"updateDate": "2020-02-21T17:50:40.3885407Z",
"catalog": {
"buildBranch": "d16.4",
"buildVersion": "16.4.29806.167",
"id": "VisualStudio/16.4.5+29806.167",
"localBuild": "build-lab",
"manifestName": "VisualStudio",
"manifestType": "installer",
"productDisplayVersion": "16.4.5",
"productLine": "Dev16",
"productLineVersion": "2019",
"productMilestone": "RTW",
"productMilestoneIsPreRelease": "False",
"productName": "Visual Studio",
"productPatchVersion": "5",
"productPreReleaseMilestoneSuffix": "1.0",
"productSemanticVersion": "16.4.5+29806.167",
"requiredEngineVersion": "2.4.1111.43337"
},
"properties": {
"campaignId": "",
"channelManifestId": "VisualStudio.16.Release/16.4.5+29806.167",
"nickname": "",
"setupEngineFilePath": "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe"
}
}
]
[ +8 ms] Building Windows application...
[ +3 ms] executing: [C:\Users\fernando.delacruz\Downloads\PCH\flutter-desktop-embedding\example\windows/] C:\src\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +21 ms] <- compile package:example_flutter/main.dart
[ +715 ms] \Windows was unexpected at this time.
[ +28 ms] Building Windows application... (completed in 0.8s)
[+10024 ms] Exception: Build process failed. To view the stack trace, please run flutter run -d windows -v.
[ +3 ms] "flutter run" took 11,875ms.

#0 throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)

#2 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#3 _rootRunUnary (dart:async/zone.dart:1134:38)
#4 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5 _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8 Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11 RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12 _rootRunUnary (dart:async/zone.dart:1134:38)
#13 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14 _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#15 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17 Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18 Future._asyncComplete. (dart:async/future_impl.dart:556:7)
#19 _rootRun (dart:async/zone.dart:1126:13)
#20 _CustomZone.run (dart:async/zone.dart:1023:19)
#21 _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:965:23)
#23 _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24 _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5).

I appreciate the help :)

**Comment by stuartmorgan** [comment]
Given the lack of vcvars banner, I suspect the issue is in your VS installation, not anything specific to Flutter. What output do you get if you execute `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat` directly?

**Comment by fer9917** [comment]
Thanks for your fast answer

./vcvars64.bat                    
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

**Comment by stuartmorgan** [comment]
> \Windows was unexpected at this time

This isn't coming from anything in Flutter-specific scripts that I can see. Searching for that generally suggests that the most likely explanation for this error is an issue in your path, which can break many common batch constructions. Do you have quoted or partially-quoted values in your path?

**Comment by fer9917** [comment]
Thank you very much, these are the variables of my path

![image](https://user-images.githubusercontent.com/14909494/75793808-82f58600-5d35-11ea-9f0e-90339eb101a8.png)

**Comment by stuartmorgan** [comment]
I don't see anything obviously problematic there.

All I can suggest as next steps would be to try manually running
```
C:\src\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
```
to verify that that is in fact what's failing, and if it is, trying to run the individual parts of that .bat script to narrow down further.

**Comment by fer9917** [comment]
I try to run the command and it throws me the following error:

`> C:\src\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug                                                                                                            x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:74
+ ... packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Micros ...
+                                                               ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by stuartmorgan** [comment]
If you're running it from a console you need to quote arguments with spaces:
```
C:\src\flutter\packages\flutter_tools\bin\vs_build.bat "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" Runner.sln Debug
```

**Comment by fer9917** [comment]
I tried again and threw this:

> C:\src\flutter\packages\flutter_tools\bin\vs_build.bat "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" Runner.sln Debug

\Common was unexpected at this time.

**Comment by stuartmorgan** [comment]
Per my earlier comment, the next step is to try reducing that script to see which part exactly is failing.

**Comment by lodestar-sr** [comment]
I think this is new issue.
My project run in windows 2 days ago, but it does not run from yesterday, after I upgrade flutter master channel. 

Here is error log.

> [   +4 ms] executing: [D:\myProject\windows/] E:\Flutter\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[  +17 ms] <- compile package:myProject/main.dart
[ +222 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.4.5
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[ +815 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +113 ms] Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +46 ms] Build started 3/4/2020 8:55:12 AM.
[ +228 ms] Project "D:\myProject\windows\Runner.sln" on node 1 (default targets).
[   +1 ms] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Debug|x64".
[ +468 ms] Project "D:\myProject\windows\Runner.sln" (1) is building "D:\myProject\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[  +98 ms] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building "D:\myProject\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[  +71 ms] InitializeBuildStatus:
[  +49 ms]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +19 ms] CustomBuildStep:
[  +12 ms]   Running Flutter backend build
[        ]   "D:\myProject\windows\scripts\prepare_dependencies" Debug
[        ]   :VCEnd
[+7750 ms] FinalizeBuildStatus:
[  +12 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[  +10 ms]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[   +2 ms] Done Building Project "D:\myProject\windows\FlutterBuild.vcxproj" (default targets).
[   +2 ms] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building "D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj.metaproj" (4) on node 1 (default
targets).
[  +13 ms] D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj" was not found.
[   +1 ms] Done Building Project "D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building
"D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj.metaproj" (5) on node 1 (default targets).
[   +1 ms] D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj" was not found.
[   +1 ms] Done Building Project "D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building "D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj.metaproj" (6) on node 1
(default targets).
[   +2 ms] D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj" was not found.
[   +1 ms] Done Building Project "D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building "D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj.metaproj" (7) on node 1
(default targets).
[   +9 ms] D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj" was not found.
[   +1 ms] Done Building Project "D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj.metaproj" (default targets) -- FAILED.
[  +69 ms] Project "D:\myProject\windows\Runner.vcxproj.metaproj" (2) is building
"D:\myProject\windows\Flutter\ephemeral\.plugin_symlinks\path_provider_fde\windows\plugin.vcxproj.metaproj" (8) on node 1 (default targets).
[  +11 ms] Project "D:\myProject\windows\Flutter\ephemeral\.plugin_symlinks\path_provider_fde\windows\plugin.vcxproj.metaproj" (8) is building
"D:\myProject\windows\Flutter\ephemeral\.plugin_symlinks\path_provider_fde\windows\plugin.vcxproj" (9) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "D:\myProject\windows\..\build\windows\intermediates\x64\Debug\path_provider_fde\path_pro.FE855771.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[ +133 ms] ClCompile:
[  +80 ms]   All outputs are up-to-date.
[  +20 ms] Link:
[   +1 ms]   All outputs are up-to-date.
[   +5 ms]   plugin.vcxproj -> D:\myProject\windows\..\build\windows\x64\Debug\Plugins\path_provider_fde_plugin.dll
[   +4 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "D:\myProject\windows\..\build\windows\intermediates\x64\Debug\path_provider_fde\path_pro.FE855771.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "D:\myProject\windows\..\build\windows\intermediates\x64\Debug\path_provider_fde\path_pro.FE855771.tlog\path_provider_fde.lastbuildstate".
[        ] Done Building Project "D:\myProject\windows\Flutter\ephemeral\.plugin_symlinks\path_provider_fde\windows\plugin.vcxproj" (default targets).
[        ] Done Building Project "D:\myProject\windows\Flutter\ephemeral\.plugin_symlinks\path_provider_fde\windows\plugin.vcxproj.metaproj" (default targets).
[   +2 ms] Done Building Project "D:\myProject\windows\Runner.vcxproj.metaproj" (default targets) -- FAILED.
[   +6 ms] Done Building Project "D:\myProject\windows\Runner.sln" (default targets) -- FAILED.
[   +6 ms] Build FAILED.
[   +7 ms] "D:\myProject\windows\Runner.sln" (default target) (1) ->
[   +1 ms] "D:\myProject\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[   +3 ms] "D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj.metaproj" (default target) (4) ->
[   +1 ms] (Build target) ->
[        ]   D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\sample\windows\sample.vcxproj" was not found.
[   +4 ms] "D:\myProject\windows\Runner.sln" (default target) (1) ->
[   +2 ms] "D:\myProject\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[   +1 ms] "D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj.metaproj" (default target) (5) ->
[        ]   D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\flutter_plugins\url_launcher_fde\windows\url_launcher_fde.vcxproj" was not found.
[   +1 ms] "D:\myProject\windows\Runner.sln" (default target) (1) ->
[        ] "D:\myProject\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[  +11 ms] "D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj.metaproj" (default target) (6) ->
[        ]   D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\window_size\windows\window_size.vcxproj" was not found.
[   +1 ms] "D:\myProject\windows\Runner.sln" (default target) (1) ->
[        ] "D:\myProject\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[        ] "D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj.metaproj" (default target) (7) ->
[        ]   D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj.metaproj : error MSB3202: The project file
"D:\myProject\windows\..\..\plugins\file_chooser\windows\file_chooser.vcxproj" was not found.
[   +1 ms]     0 Warning(s)
[        ]     4 Error(s)
[        ] Time Elapsed 00:00:09.12
[  +94 ms] Building Windows application... (completed in 10.5s)
[ +582 ms] Exception: Build process failed. To view the stack trace, please run `flutter run -d windows -v`.
[   +3 ms] "flutter run" took 11,978ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Finally, I think the issues are:
https://github.com/google/flutter-desktop-embedding/tree/master/plugins  
The `plugin` directory has not proper project files `*.vcxproj` inside each plugin subdirectories.

**Comment by stuartmorgan** [comment]
@lodestar-sr Your compile failures have nothing to do with this issue, you just haven't updated for a recent breaking change. See my recent post about plugins on the mailing list.

**Comment by lodestar-sr** [comment]
@stuartmorgan I checked flutter mailing list, I got the clue from this https://groups.google.com/forum/#!topic/flutter-desktop-embedding-dev/yqHPgXcS59k
Thanks.

**Comment by stuartmorgan** [comment]
Closing due to lack of response.
