### ISSUE TITLE
[macOS] keyevent not implemented

### ISSUE THREAD

**Issue by maun** [google/flutter-desktop-embedding#72]
The keyDown/keyUp events which should be sent over the "flutter/keyevent" channel are not implemented in the macOS embedder. Because of that RawKeyboardListener does not work.

I got a working version in this branch: https://github.com/maun/flutter-desktop-embedding/commit/b6bdb2803d68a80b800ba2895dd28ca5531980d5

What would be necessary for a PR?

**Comment by stuartmorgan** [comment]
Cool!

You'll need to sign the CLA as described at https://github.com/google/flutter-desktop-embedding/blob/master/CONTRIBUTING.md but otherwise just go ahead and send a PR and I can review it.

(A quick note from glancing at it: it looks like all the new code is using four space indentation; code should follow the Google style guide: http://google.github.io/styleguide/objcguide.html. I'd recommend running clang-format over all the files you've edited.)

**Comment by stuartmorgan** [comment]
I'm going to close this as fixed, and remaining work can be tracked in follow-ups if/when anyone needs more functionality (e.g., modifiers) before #47 is addressed.
