### ISSUE TITLE
Why I can't build the flutter application for windows?

### ISSUE THREAD

**Issue by YowFung** [google/flutter-desktop-embedding#791]
I wrote a flutter application and it can run at the Android platform. Now I'll make it run at Windows platform, but it throws an exception when I executed flutter run -d "windows".

The details of this issue are posted on another issue: [(flutter/flutter issues #65147)](https://github.com/flutter/flutter/issues/65147).

**Comment by stuartmorgan** [comment]
Please read https://github.com/google/flutter-desktop-embedding#feedback

**Comment by stuartmorgan** [comment]
Ah, I see from the other issue that your issue was with window_size. In the future, please post actual details when you file an issue rather than referring elsewhere.

Based on the error messages, you are using an old version of the window_size plugin. As the readme says, breaking changes are common. The only version combinations that are supported for this project are the latest version of Flutter master and the latest version of the code here. If you want to use old versions for some reason, it's up to you to find compatible versions across the two projects.

**Comment by YowFung** [comment]
@stuartmorgan Thank you for your answer! I am still a novice. Do not really understand the rules about posting issues. thank you for reminding me and I will pay attention in the future~~
