### ISSUE TITLE
[file_chooser] Allow choosing files and directories simultaneously

### ISSUE THREAD

**Issue by jagmit** [google/flutter-desktop-embedding#813]
It would be nice to allow configuring the file chooser in such a way that both files and directories could be chosen in it simultaneously.
Currently setting the `canSelectDirectories` flag to true or false causes the file chooser to allow _only_ directories or files.

For macOS this is technically possible, `NSOpenPanel` allows setting the `canChooseFiles` and `canChooseDirectories` flags simultaneously ([this line](https://github.com/google/flutter-desktop-embedding/blob/85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3/plugins/file_chooser/macos/Classes/FLEFileChooserPlugin.m#L92) would need to be changed).

I was not able to check whether the native file chooser dialogs on Windows and Linux allow this, but I would love to help implement this issue if this is regarded as something useful.

**Comment by stuartmorgan** [comment]
That doesn't work on Windows, and IIRC it didn't on Linux either, which is why macOS is set up that way; it seemed less confusing to have the functionality be consistent across the desktop platforms.

There will be no further functionality changes to `file_chooser` however, as it will be replaced with https://github.com/flutter/plugins/tree/master/packages/file_selector shortly; new requests like this should be filed against that plugin.
