### ISSUE TITLE
Save File with XFile return blank file in MacOS

### ISSUE THREAD

**Issue by MasIzzudin** [google/flutter-desktop-embedding#842]
I don't know if this is a bugs or i missed something, 
but i try to follow the code from example how to save text.
even i copy paste all the code from example, but when it saving the file, 
it is not return with format file, it just blank file

![Screen Shot 2021-03-23 at 01 54 17](https://user-images.githubusercontent.com/28093630/112043588-695ef080-8b7b-11eb-9c0a-b21c3f0d5ae8.png)
![Screen Shot 2021-03-23 at 01 55 16](https://user-images.githubusercontent.com/28093630/112043595-6bc14a80-8b7b-11eb-9b01-6554952b5197.png)
![Screen Shot 2021-03-23 at 01 55 40](https://user-images.githubusercontent.com/28093630/112043600-6d8b0e00-8b7b-11eb-891c-9ac6d3533deb.png)
![Screen Shot 2021-03-23 at 01 57 31](https://user-images.githubusercontent.com/28093630/112043602-6e23a480-8b7b-11eb-965a-1539c84bbb91.png)
![Screen Shot 2021-03-23 at 01 58 00](https://user-images.githubusercontent.com/28093630/112043606-6ebc3b00-8b7b-11eb-92f2-f0de594a95aa.png)
![Screen Shot 2021-03-23 at 01 58 12](https://user-images.githubusercontent.com/28093630/112043611-6f54d180-8b7b-11eb-96b8-b4f505f7792b.png)

**Comment by stuartmorgan** [comment]
The only part of this flow that the plugin implementation in this repository is responsible for is showing the dialog and returning the selected path to the main plugin. Based on your screenshots, that step is working since you have a dialog, and a file in the right place. Given that, there's no bug in file_selector_macos here.

If you have issues with file_selector, or cross_file, you'll need to file issues against those packages; neither is part of this repository.
