### ISSUE TITLE
Improve desktop support

### ISSUE THREAD

**Issue by gabrc52** [google/flutter-desktop-embedding#91]
Here are some ideas to make Flutter better for desktop platforms:

- [ ] Showing tooltips when the mouse pointer hovers over a widget with a tooltip (not sure if this is not implemented in this project or Flutter as a whole)
- [ ] Clipboard integration
- [ ] Select text from text fields with keyboard and use Ctrl+C and Ctrl+V
- [ ] More keyboard integration, e.g. switching between widgets with the Tab key
- [ ] Ability to scroll a ListView with mouse wheel

**Comment by stuartmorgan** [comment]
Since improving the experience of running Flutter on desktop is the overarching goal of this whole project, and each of these would be a non-trivial undertaking with different approaches and limitations, I don't think tracking them in one bug is viable. Please file each specific request as a separate bug though (many of these are already on my mental list, I just haven't filed everything I'd like to explore; having a bug tracking each one would be useful).

**Comment by stuartmorgan** [comment]
I went ahead and filed 92-97, which I think covers most of what's here. If you have other specific requests, please file them!
